export const listData = [
    {
      id: 1,
      title: "A Great Apartment Next to the Beach!",
      images: ["https://images.pexels.com/photos/1918291/pexels-photo-1918291.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"],
      bedroom: 2,
      bathroom: 1,
      price: "45 Lakhs",
      address: "Green Park, Delhi, India",
      latitude: 28.558899,
      longitude: 77.202805,
    },
    {
      id: 2,
      title: "An Awesome Apartment Near the Park! Almost too good to be true!",
      images: ["https://images.pexels.com/photos/1428348/pexels-photo-1428348.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"],
      bedroom: 3,
      bathroom: 2,
      price: "90 Lakhs",
      address: "Ambedkar Nagar, Uttar Pradesh, India",
      latitude: 26.407057,
      longitude: 82.397972,
    },
    {
      id: 3,
      title: "A New Apartment in the City!",
      images: ["https://images.pexels.com/photos/2062426/pexels-photo-2062426.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"],
      bedroom: 1,
      bathroom: 1,
      price: "1.25 Cr.",
      address: "Janak Nagar, Saharanpur, Uttar Pradesh, India ",
      latitude: 29.957846,
      longitude: 77.554115,
    },
    {
      id: 4,
      title: "Great Location! Great Price! Great Apartment!",
      images: ["https://images.pexels.com/photos/2467285/pexels-photo-2467285.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"],
      bedroom: 2,
      bathroom: 1,
      price: "60 Lakhs",
      address: "Mauli Baidwan, Sahibzada Ajit Singh Nagar, Punjab, India,",
      latitude: 30.678722,
      longitude: 76.722153,
    },
    {
      id: 5,
      title: "Apartment 5",
      images: ["https://images.pexels.com/photos/276625/pexels-photo-276625.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"],
      bedroom: 3,
      bathroom: 2,
      price: "75 Lakhs",
      address: "Vasna, Ahmedabad, Gujarat, India",
      latitude: 23.003992,
      longitude: 72.546074,
    },
    {
      id: 6,
      title: "Apartment 6",
      images: ["https://images.pexels.com/photos/271816/pexels-photo-271816.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"],
      bedroom: 1,
      bathroom: 1,
      price: "19 Lakhs",
      address: "Nawabganj, Kanpur, Uttar Pradesh, India",
      latitude: 26.492607,
      longitude: 80.301811,
    },
    {
      id: 7,
      title: "Apartment 7",
      images: ["https://images.pexels.com/photos/2029667/pexels-photo-2029667.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"],
      bedroom: 2,
      bathroom: 1,
      price: "1.2 Cr.",
      address: "Rampur Garden, Bareilly, Uttar Pradesh, India",
      latitude: 28.352783,
      longitude: 79.423973,
    },
    {
      id: 8,
      title: "Apartment 8",
      images: ["https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"],
      bedroom: 3,
      bathroom: 2,
      price: "15 Lakhs",
      address: "Sangam Vihar, Delhi, India",
      latitude: 28.497511,
      longitude: 77.240585,
    },
  ];
  
  export const singlePostData = {
    id: 1,
    title: "Beautiful Apartment",
    price: "12 Lakhs",
    images: [
      "https://images.pexels.com/photos/1918291/pexels-photo-1918291.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/1428348/pexels-photo-1428348.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/2062426/pexels-photo-2062426.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/2467285/pexels-photo-2467285.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    videos: "https://youtu.be/R8OejFuUYqo",
    bedRooms: 2,
    bathroom: 1,
    size: 861,
    latitude: 26.791519,
    longitude:  83.360237,
    city: "Gorakhpur",
    address: "Dayanand Nagar, Uttar Pradesh, India",
    school: "250m away",
    bus: "100m away",
    restaurant: "50m away",
    description:
      "Future alike hill pull picture swim magic chain seed engineer nest outer raise bound easy poetry gain loud weigh me recognize farmer bare danger. actually put square leg vessels earth engine matter key cup indeed body film century shut place environment were stage vertical roof bottom lady function breeze darkness beside tin view local breathe carbon swam declared magnet escape has from pile apart route coffee storm someone hold space use ahead sheep jungle closely natural attached part top grain your grade trade corn salmon trouble new bend most teacher range anybody every seat fifteen eventually",
  };
  
  export const userData = {
    id: 1,
    name: "Vinay Poonia",
    img: "./image.jpeg",
  };